spring.application.name=backend

# MYSQL CONNECTION SETTINGS
spring.datasource.url=jdbc:mysql://localhost:3309/datastreamx?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=your username
spring.datasource.password=your password

# HIBERNATE SETTINGS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
